### ISSUE TITLE
Publish on Open-VSX?

### ISSUE THREAD

**Issue by iamjameswalters** [dz4k/vscode-hyperscript#1]
This is a lifesaver--thank you @dz4k for writing this! :heart: 

Is there any chance we could also get this put up on [Open VSX](https://open-vsx.org/)? I'm a [Codium](https://vscodium.com/) user at home and would love to install this there.

**Comment by dz4k** [comment]
It's already on there!

https://open-vsx.org/extension/dz4k/vscode-hyperscript-org

**Comment by iamjameswalters** [comment]
Ah! Brilliant. :+1: Sorry I missed that somehow!
